source 'https://rubygems.org' do
  gem 'bootsnap'
  gem 'bootstrap-sass'
  gem 'coffee-rails'
  gem 'dragonfly', git: 'git@github.com:markevans/dragonfly.git'
  gem 'draper'
  gem 'execjs'
  gem 'font-awesome-sass', '~> 5.12.0'
  gem 'friendly_id'
  gem 'haml-rails'
  gem 'jquery-rails'
  gem 'jquery_mobile_rails'
  gem 'listen'
  gem 'nokogiri'
  gem 'paper_trail'
  gem 'paranoia'
  gem 'pg'
  gem 'pry'
  gem 'puma'
  gem 'rack-cors', require: 'rack/cors'
  gem 'rails', '6.0.2.1'
  gem 'redis'
  gem 'redis-rails'
  gem 'redis-rack-cache'
  gem 'sass-rails'
  gem 'sidekiq'
  gem 'sinatra', require: nil
  gem 'sunspot_rails'
  gem 'sunspot_solr'
  gem 'swipebox', git: "git@github.com:ngonzalez/swipebox.git"
  gem 'taglib-ruby'
  gem 'tilt', require: 'tilt/sass'
  gem 'uglifier'
  gem 'uuid'
  gem 'whenever'
end
