source 'https://rubygems.org' do
  gem 'bootsnap'
  gem 'bootstrap-sass'
  gem 'coffee-rails'
  gem 'dragonfly', git: 'git@github.com:markevans/dragonfly.git'
  gem 'draper'
  gem 'font-awesome-sass', '4.7.0'
  gem 'friendly_id'
  gem 'haml-rails'
  gem 'jquery-rails'
  gem 'jquery_mobile_rails'
  gem 'listen'
  gem 'nokogiri'
  gem 'paper_trail'
  gem 'paranoia'
  gem 'pg'
  gem 'progress_bar'
  gem 'pry'
  gem 'puma'
  gem 'rack-cache', require: 'rack/cache'
  gem 'rack-cors', require: 'rack/cors'
  gem 'rails', '5.2.3'
  gem 'redis'
  gem 'sass-rails'
  gem 'sidekiq'
  gem 'sinatra', require: nil
  gem 'sunspot_rails'
  gem 'sunspot_solr'
  gem 'swipebox'
  gem 'taglib-ruby'
  gem 'tilt', require: 'tilt/sass'
  gem 'typhoeus'
  gem 'uglifier'
  gem 'uuid'
  gem 'whenever'
end
