---
AAC:
  default: true
  :tags:
    - AAC
  :extensions:
    - aac
    - m4a
    - mp4
AIFF:
  :tags:
    - AIFF
  :extensions:
    - aif
    - aiff
ALAC:
  :tags:
    - ALAC
  :extensions:
    - m4a
MP3:
  :tags:
    - Audio file with ID3
    - MPEG ADTS
  :extensions:
    - mp3
WAV:
  :tags:
    - WAV
  :extensions:
    - wav
