BASE_PATH = "/Volumes/My\ Drive/music"
HLS_FOLDER = "/tmp/hls"
ALLOWED_AUDIO_FORMATS = ["mp3", "mp4", "m4a", "flac", "wav", "aiff", "aif"]
ALLOWED_IMAGE_FORMATS = ["jpg", "JPG", "jpeg", "JPEG"]
ALLOWED_SOURCES = ["WEB", "Vinyl", "CD", "Live", "TAPE", "FLASH"]
NFO_TYPE = "nfo"
SFV_TYPE = "sfv"
M3U_TYPE = "m3u"
DEFAULT_ENCODING = "mp3"
HOST_NAME = "example.net"
FOLDERS = ["music"]
FOLDERS_WITH_SUBFOLDERS = ["backup"]
EXCEPT_GRPS = /EXAMPLE/
EXCEPT_RLS = []
SUPPORTED_AUDIO_FORMATS = {
  "MPEG ADTS" => "MP3",
  "Audio file with ID3" => "MP3",
  "AAC" => "AAC",
  "AIFF" => "AIFF",
  "ALAC" => "ALAC",
  "FLAC" => "FLAC",
  "WAV" => "WAV",
}
