# BASE_PATH = "/Volumes/FreeAgent\ GoFlex\ Drive/music"
BASE_PATH = "/Volumes/Seagate\ Backup\ Plus\ Drive/music"
ALLOWED_METRICS = ["format_name", "genre", "year", "bitrate"]
ALLOWED_AUDIO_FORMATS = ["mp3", "mp4", "m4a", "flac", "wav", "aiff"]
ALLOWED_IMAGE_FORMATS = ["jpg", "JPG", "jpeg", "JPEG", "gif", "png", "tiff", "bmp"]
ALLOWED_SOURCES = ["WEB", "Vinyl", "CD", "SAT-CABLE", "Line", "Live", "Tape"]
NFO_TYPE = "nfo"
SFV_TYPE = "sfv"
SFV_CHECK_APP = "cfv"
DEFAULT_ENCODING = "mp3"
LABELS = []
HOST_NAME = "example.net"
BITLY_TOKEN = "REPLACE_TOKEN"
FOLDERS = ["dnb","hc","other"]
FOLDERS_WITH_LABELS = ["backup"]
EXCEPT_GRPS = /EXAMPLE_INT|ABCD_INT/
