BASE_PATH               = "/Volumes/External\ Drive"
HLS_FOLDER              = "/tmp/hls"
DEFAULT_ENCODING        = "mp3"
HOST_NAME               = "example.com"
ALLOWED_AUDIO_FORMATS   = YAML.load_file Rails.root.join('config/yaml/allowed_audio_formats.yaml')
ALLOWED_IMAGE_FORMATS   = YAML.load_file Rails.root.join('config/yaml/allowed_image_formats.yaml')
ALLOWED_SOURCES         = YAML.load_file Rails.root.join('config/yaml/allowed_sources.yaml')
FOLDERS                 = YAML.load_file Rails.root.join('config/yaml/folders.yaml')
FOLDERS_WITH_SUBFOLDERS = YAML.load_file Rails.root.join('config/yaml/folders_with_subfolders.yaml')
EXCEPT_RLS              = YAML.load_file Rails.root.join('config/yaml/except_rls.yaml')
EXCEPT_NAMES            = YAML.load_file Rails.root.join('config/yaml/except_names.yaml')
SUPPORTED_AUDIO_FORMATS = YAML.load_file Rails.root.join('config/yaml/supported_audio_formats.yaml')
