local_defaults: &local-defaults
  adapter: postgresql
  encoding: utf8
  username: enyo
  password: 

development:
  <<: *local-defaults
  database: music

test:
  <<: *local-defaults
  database: music_test

production:
  <<: *local-defaults
  database: music
