local_defaults: &local-defaults
  adapter: postgresql
  encoding: utf8
  username: enyo
  password: postgres

development:
  <<: *local-defaults
  database: music

test:
  <<: *local-defaults
  database: music_test

remote_defaults: &remote-defaults
  adapter: postgresql
  encoding: utf8
  username: postgres
  password:

staging:
  <<: *remote-defaults
  database: staging

production:
  <<: *remote-defaults
  database: production