local_defaults: &local-defaults
    hostname: <%= SUNSPOT_SOLR_HOSTNAME %>
    port: <%= SUNSPOT_SOLR_PORT %>
    path: <%= SUNSPOT_SOLR_PATH %>

production:
  solr:
    <<: *local-defaults
    log_level: WARNING

development:
  solr:
    <<: *local-defaults
    log_level: INFO
