local_defaults: &local-defaults
    hostname: <%= SOLR_HOST %>
    port: <%= SOLR_PORT %>
    path: <%= SOLR_PATH %>

development:
  solr:
    <<: *local-defaults
    log_level: INFO

production:
  solr:
    <<: *local-defaults
    log_level: WARNING
