---
    - 7INCH
    - VINYL
    - VLS
    - CDA
    - CDS
    - CDM
    - 2CD
    - EP
    - CDEP
    - LP
    - CDR
    - DVD
    - (Bootleg)
    - (Promo_CD)
    - (Promo_CDS)
    - (Promo_WEB)
    - (Full)
    - (FULL)
    - (Web)
    - (WEB)
    - Bootleg
    - Promo_CD
    - Promo_CDS
    - Promo_WEB
    - Full
    - Repack
    - Promo
    - Proper
    - Single
    - Retail
    - VA
    - REPACK
    - RETAIL
    - SINGLE
    - BONUS_TRACKS
    - PROPER
    - READNFO
    - READ_NFO
    - BR
    - ES
    - FR
    - IT
    - SP
    - JP